### ISSUE TITLE
TestCentric gets stuck in running state after the tests are completed

### ISSUE THREAD

**Issue by ideafixxxer** [TestCentric/testcentric-gui#321] opened 2019-04-11 18:12 UTC
After tests selected under a selected test fixture are run (some passed, some failed) button Run remains disabled. Clicking button Stop doesn't do anything either.
Status bar shows: Tests: 23 Run: 23 Passed: 19 Failed: 4

**Comment by mikkelbu** [comment] 2019-04-12 19:07
The Run button is (indirectly) hooked up on properties from the engine (that there are tests, and that the tests are not running). What happens if you run the same tests using the nunit-console?

**Comment by CharliePoole** [comment] 2019-04-12 20:45
Also, can you indicate what build of testcentric you are running?

**Comment by ideafixxxer** [comment] 2019-04-15 18:28
@CharliePoole I'm running Alpha4

@mikkelbu nunit3-console runs the tests successfully (same as GUI). And exits.

**Comment by ideafixxxer** [comment] 2019-04-25 14:09
Event **test-run** never fires in the dispatcher.
On Beta now.

**Comment by CharliePoole** [comment] 2019-04-26 15:42
@ideafixxxer I'm not able to reproduce this. Can you give some more exact instructions about how you are selecting and running tests?

**Comment by ideafixxxer** [comment] 2019-04-29 23:44
@CharliePoole I found the issue. It happened because my test project used NUnit.framework v3.5.
After upgrading to the latest v3.11 the tests stopped loading at all (I don't know why).
After downgrading to v3.10.1 it finally works.
With 3.5 the ProcessRunner would return `null` instead of XML. As result `TestEngineResult.XmlNodes` would generate `NullReferenceException`, preventing setting `IsTestRunning` to true and not bubbling up or being logged whatsoever. 
Please add try-catch-finally to `MasterTestRunner.RunTests`.

**Comment by CharliePoole** [comment] 2019-04-30 07:10
Hmm... Whichever version of the framework you use, you are still using the engine version that is bundled with the GUI, which has some special modifications. They could be in error.

If you have time, it would be useful to know how the console runner deals with your tests when you use the 3.5 framework. Specifically, does it save the test result XML correctly? If it does, then it's either the GUI or it's special engine build that is at fault.

I'd be very surprised if the 3.5 framework is failing to return anything. We would have heard about it, I think.

**Comment by ideafixxxer** [comment] 2019-04-30 13:25
I was surprised myself when I realized it pick up nunit.framework.dll from the test target. I spent whole day not understanding why my debugger doesn't step into it. There is a lot of domain and remoting magic going on and it times it's hard to understand what's called from where.
I don't have time right now, but I would also check `RunTestsCallbackHandler.IsFinalResult` with 3.5 output.

**Comment by CharliePoole** [comment] 2019-04-30 13:47
`RunTestsCallBackHandler.IsFinalResult` is my suspect as well. If you read the comments, you know that it is tryig to make up for a deficiency in the original design, i.e. the fact that progress and final result use the same channel. It may be that 3.5 results are not being recognized as final.

**Comment by CharliePoole** [comment] 2019-06-04 15:51
I'm unable to confirm this. I tried selecting various items and all ran correctly. I also looked at the output from V3.5 and it conforms to what `RunTestsCallBackHandler.IsFinalResult` expects. The final result has an `environment` element and is immediately recognized.

Looking at the code, I do see that it could be sensitive to exactly what you are selecting. Can you tell me what the level of namespace and/or fixture nesting is and where you are making the selection? Alternatively, a working example would help, if possible.

For a different issue, a try block is being added to `MasterTestRunner.RunTests`, where the `catch` block causes a message to be displayed. When that is merged I'll let you know in case you want to try it with tests.

**Comment by CharliePoole** [comment] 2019-07-04 00:34
Closing this lacking more info and being unable to reproduce it with the current code. If you come up with a repro, we can reopen.

**Closed by CharliePoole** 2019-07-04 00:34 UTC
Labels: confirm
