### ISSUE TITLE
Clear all does not work

### ISSUE THREAD

**Issue by YBB8201** [TestCentric/testcentric-gui#594] opened 2020-07-20 05:23 UTC
when I mark several tests (check their check boxes), and I try to clear all marks using "clear all" button, the check box stays checked. 

**To Reproduce**
1. check several tests check box
2. click on "clear all"

**Expected behavior**
all marked check box will stay in their original state

**Screenshots**
If the bug is visual in nature, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - TestCentric Version [e.g. 1.4.1]
 - OS: windows 7
 - Target Runtime for your test assembly: .NET Framework 4.7.2

**Comment by CharliePoole** [comment] 2020-07-20 08:33
You indicated you are running TestCentric 1.4.1, running on Windows 7 and targeting .NET Framework 4.7.2.

However, the latest release of TestCentric was 1.4.0. Please say what version you are actually running and verify that the other info is correct. Also, please say how you installed TestCentric, e.g. from nuget, using chocolatey, etc.

**Comment by YBB8201** [comment] 2020-07-21 09:42
Hi,
I am using TestCentric 1.4.0 running on Windows 7 and targeting .NET Framework 4.7.2.
I download tescentric as nuget package using visual studio.

**Comment by CharliePoole** [comment] 2020-07-23 12:32
I created a project on a Windows7 as you describe. I'm unable to reproduce the error. I can check various combinations of tests as well as uncheck them. The Clear All button worked correctly.

I'm closing this issue but if you come up with any further info that would allow reproducing it, I'll see it if you add a comment.

**Closed by CharliePoole** 2020-07-23 12:32 UTC

**Comment by CharliePoole** [comment] 2020-12-01 01:55
This did turn out to be a problem under specific circumstances documented in #607. It has been fixed in PR #608

**Comment by YBB8201** [comment] 2020-12-01 05:18
Great, thx

בתאריך יום ג׳, 1 בדצמ׳ 2020, 03:56, מאת CharliePoole ‏<
notifications@github.com>:
