### ISSUE TITLE
`ArgumentNullException` parameter `tests` at `TestCentric.Gui.Model.TestModel.RunTests(TestSelection tests)`

### ISSUE THREAD

**Issue by maettu-this** [TestCentric/testcentric-gui#1045] opened 2024-04-12 06:28 UTC
This issue is extracted from https://github.com/TestCentric/testcentric-gui/issues/1043 as it is an additional finding.

**Describe the bug**
See ["TestCentric 2.0.0-beta4 with SetUpFixture workaround"](https://github.com/TestCentric/testcentric-gui/issues/1043#issue-2230459050) resulting in:
![320388447-c914d5ee-8e1a-4ca3-8feb-9c77218be1d4](https://github.com/TestCentric/testcentric-gui/assets/24897735/6b0d6502-46cf-4178-95d6-29d857b05d4e)

**To Reproduce**
1. Build [TextOutputIssue.zip](https://github.com/TestCentric/testcentric-gui/files/14902096/TextOutputIssue.zip)
2. Open the assembly in TC 2.0.0-beta4

**Expected behavior**
No exception. Even better, an error message describing the why no tests could be loaded.

**Screenshots**
See above.

**Environment (please complete the following information):**
 - TestCentric Version 2.0.0-beta4
 - OS: Win10
 - Target Runtime for your test assembly: .NET Framework 4.8

**Comment by CharliePoole** [comment] 2024-04-13 14:30
Same as #1044. I'm not seeing the issue.... there is no crash. Your trace output does appear, but after the specific Progress outputs. Looking more closely, this seems to be the correct code for #1045.

**Comment by maettu-this** [comment] 2024-04-13 19:21
This one is more tricky, I cannot reproduce each time either. I have tried to find a way to make it reproduce each time, e.g. just the first time after having installed TC, or after having switched from TC 1.6.4 to 2.0.0-beta4, but haven't found a reliable way so far.

> trace output does appear, but after the specific Progress outputs

This is expected, the above linked [TextOutputIssue.zip](https://github.com/TestCentric/testcentric-gui/files/14902096/TextOutputIssue.zip) is the initial version using the `ConsoleTraceListener`.

You can also try with [TextOutputIssue.with.ProgressTraceListener.zip](https://github.com/TestCentric/testcentric-gui/files/14910397/TextOutputIssue.with.ProgressTraceListener.zip). That outputs text in correct sequence, but appart from that, it also sometimes lets TC crash and running the same test multiple times also results in multiplicated output.

**Comment by CharliePoole** [comment] 2024-05-08 23:54
Something is off here. You describe this as happening when the tests are loaded but the exception you show indicates it was thrown when running the tests. In any case, I cannot reproduce this so I'll close it. We can re-open if you find a reliable repro.

**Closed by CharliePoole** 2024-05-08 23:54 UTC
Labels: Bug, Needs Confirmation
