### ISSUE TITLE
ReportPortal addins to TestCentric

### ISSUE THREAD

**Issue by eddie101AMR** [TestCentric/testcentric-gui#558] opened 2020-04-03 22:58 UTC
Hi,
I'm trying to run tests via TestCentric.GuiRunner.1.3.2, but I can't see the results uploaded to ReportPortal, I added ReportPortal.addins to TestCentric folder in packages folder,
the same thing I did with NUnit.ConsoleRunner.3.11.1 and it's working fine when I run my tests via Nunit console runner,
Do you support ReportPortal addins?
what I'm missing? any ideas ?
Is there any TestCentric logs that can I look at or upload them to you in order to investigate?
Where can I find them?

Thanks
Eddie

**Comment by CharliePoole** [comment] 2020-04-04 00:48
Is the addin found when you select Tools | Extensions?

**Comment by eddie101AMR** [comment] 2020-04-04 07:10
Thanks for the fast response, 
I installed TestCentric from VS NuGet package manager, and also the ReportPortal from NuGet package manger, just like the Nuint console runner,
After the installation, I copied the ReportPortal.addins to TestCentric package folder in my solution.
Did I miss something or should I install it in a different way?
Because I did the same with nunit console runner, and it's working flawlessly.

Thanks
Eddie

**Comment by CharliePoole** [comment] 2020-04-04 16:41
I don't think it makes a great difference, but please let me know what version of ReportPortal you are using. The rest of this applies to 3.7.15 and 4.0.0-beta.1. I examined the content of their packages but didn't install it myself.

What I see is that there are two things conspiring to cause the problem...

1. The ReportPortal nuget package is not organized as NUnit expects it. They placed the extension in a lib subdirectory, whereas all the extensions published by the NUnit Project use the tools directory. In order to compensate for this, they give some instructions about creating an addins file. Those instructions are tailored to use with NUnit3-console of course. In fact, you should not need to create a file at all for this to work.

2. The TestCentric GUI may seems to have an error in its own addins files, which prevents the addins from being found.

I've made this a high priority but, unfortunately, that means it competes for my time with all the other high-priority stuff. If you're willing to do some work to find the best solution I'll promote this issue to critical and do a 1.3.3 release when we fix it. If you are, here are some experiments to perform.

1. Run the GUI, leaving your addins file in place, and verify that ReportPortal is not called.
2. Use the file menu to re-load the test in-process and re-run it. Is ReportPortal used?
3. Remove your addins file temporarily as it will be in the way for the next steps.
4. Go into the packages directory and find the ReportPortal package. Rename it's `lib` directory to `tools`. This essentially fixes what I see as the ReportPortal side of the problem.
5. Repeat steps 1 and 2, running the test in-process and out of process. What happens?

Based on what I have seen in the code, I suspect that both steps 2 and 5 will succeed when the test is run in-process. But, if not, we can go on from there with the information you collect. In either case, I'll give you some fixes to try that don't require changing the ReportPortal package.

BTW it's entirely possible that what __I__ see as the "ReportPortal side of the problem" is actually a consious design decision on their part. They may have wanted the extension to be copied to the output directory for other reasons. The NUnit console does not normally expect that but knows how to deal with it. I suspect that the GUI only deals with it when run in-process. The key difference is that the console runner has agents in the root directory while the GUI had them in multiple subdirectories. NUnit will probably be going the same way once it has separate agents for .NET Core.

**Comment by CharliePoole** [comment] 2020-04-04 20:21
From discussions with @nborisenko on ReportPortal/agent-net-nunit#58, I think that this needs to be entirely fixed using tailored addins files. Once you get back to me with results on the experiments above I'll create something you can try.

**Comment by CharliePoole** [comment] 2020-04-05 01:24
@eddie101AMR Have you had a chance to try any of the steps I listed? Here's a shorter list based on discussions with @nborisenko and reviewing the code.

1. Try to run the tests in-process. I believe it should work. If not, let me know.
2. If 1 works, copy your addins file to each target directory under agents. Edit the file so that the relative path still points to your extension... IOW just add more `..` segments. This should work when running using the default out-of-process settings.

Let me know what works!

**Comment by eddie101AMR** [comment] 2020-04-05 08:32
@CharliePoole 
thanks for taking this issue very seriously,

1. I tried to run the test in process with the ReportPortal.addins in the main directory but it didn't called the reportportal, and I couldn't see that the reportportal extension in the extensions window in TestCentric,
2. I also added ReportPortal.addins to each target directory under agents and modified the relative path to the directory whereReportPortal.NUnitExtension.dll
..\..\..\..\KLA.OMD.Framework\bin\Debug\ReportPortal.NUnitExtension.dll
and still didn't called the reportportal, and I couldn't see that the reportportal extension in the extensions window in TestCentric.

for some reason TestCentric is not loading the ReportPortal extension.

** building local ReportPortal server on Ubuntu with Docker take about 10 minutes with the instruction in ReportPortal website, 
maybe it will help you debug the issue.

Thanks
Eddie

**Comment by nvborisenko** [comment] 2020-04-06 12:56
https://github.com/TestCentric/testcentric-gui/blob/6df2ee906af608efc07197cae7be6aef1b0db8a5/src/TestEngine/testcentric.engine.core/Services/ExtensionService.cs#L440

@CharliePoole, should extension use this attribute, which is not from `nunit.enine.api`?

**Comment by CharliePoole** [comment] 2020-04-06 15:48
@nvborisenko Yes, it's intended for that purpose and it is definitely defined in the api assemblies:

NUnit: https://github.com/nunit/nunit-console/blob/master/src/NUnitEngine/nunit.engine.api/Extensibility/ExtensionPropertyAttribute.cs

TestCentric: https://github.com/TestCentric/testcentric-gui/blob/master/src/TestEngine/testcentric.engine.api/Extensibility/ExtensionPropertyAttribute.cs

However, as I answer you, I did just realize that creating a __separate__ api assembly for TestCentric could be a problem for those who want to write extensions. In the case of the Attributes, it seems to be working OK but I need to review __every__ Type in the API assembly to be sure.

For compatibility, it may be better if  I go back to using the NUnit assembly itself in some way! Ouch!

**Comment by eddie101AMR** [comment] 2020-04-06 16:32
@CharliePoole did you have the chance to look at my reply?
Is there any new things that I can try in order to make it work?

**Comment by CharliePoole** [comment] 2020-04-06 17:07
@eddie101AMR I did see it. Sorry for not answering you. I think I need to set up some experiments of my own using the 1.3.2 release rather than the newer code I am now testing as wekk as actually using the ReportPortal extension. That may take me a few days.

See my previous comment to @nvborisenko for an explanation of why one extension may work (the ones I have been testing with) while another may not.

**Comment by CharliePoole** [comment] 2020-04-06 17:08
Raising this to critical at least until I can determine whether the use of a separate API assembly is causing a problem. Nevertheless, I have to clear the decks of a few other things before i can really work on this one.

**Comment by eddie101AMR** [comment] 2020-04-06 19:14
@CharliePoole thank you : )
I'll wait for more information from you.
have a great day.

**Comment by nvborisenko** [comment] 2020-04-06 19:50
To summarize: TestCentric doesn't support nunit extensions. To make it possible it's pain as for TestCentric as for ReportPortal. Will be optimistic :)

**Comment by eddie101AMR** [comment] 2020-04-06 22:05
@nvborisenko does it mean that there is no way that @CharliePoole  can fix this from his side : ( ,
I really need it for a project at work  and there is no other way to run tests from a GUI test runner that supports ReportPortal,
one painful way is to develop GUI test runner that uses NUnit console runner  : S

**Comment by nvborisenko** [comment] 2020-04-07 08:06
@eddie101AMR seems it will be possible, but it needs a time.

You can try Visual Studio Test Explorer: https://github.com/reportportal/agent-net-nunit/issues/44

**Comment by CharliePoole** [comment] 2020-04-07 22:16
I have confirmed that no nunit extensions are loading in 1.3.2. In fact, this may have been the case in 1.3.1 and 1.3.0 as well.

**Comment by CharliePoole** [comment] 2020-04-14 01:30
@eddie101AMR @nvborisenko 

A fix is available at https://ci.appveyor.com/api/buildjobs/lvs9cg80gexrdamg/artifacts/package%2FTestCentric.GuiRunner.1.3.3-pr00561-20.nupkg

It's currently under review prior to merging and creating a new release.

It would be great if someone could actually try it out with ReportPortal.

**Comment by nvborisenko** [comment] 2020-04-14 10:02
Works.

**Comment by CharliePoole** [comment] 2020-04-14 11:05
Good! I'll get out a new release as soon as possible.

**Comment by eddie101AMR** [comment] 2020-04-15 09:41
Thanks @CharliePoole  !!
I'll try it tomorrow,
Can you estimate when will it be available on NuGet packages from the visual studio?

**Comment by CharliePoole** [comment] 2020-04-15 15:05
I'm waiting for a code review before merging. Unfortunately, since the API assembly was completely replaced to resolve the issue, that takes time, perhaps a few days. Once merged there will be an immediate release.

Of course, you can already install this from Visual Studio by adding our the package to a local source folder you create.

**Comment by eddie101AMR** [comment] 2020-04-15 21:30
yeah, I know that I can add the package to my local source and install it from there,
I meant when will be an official release, I'll test what you shared and I'll install the official release once it released.
Thanks

**Comment by eddie101AMR** [comment] 2020-04-16 06:52
@CharliePoole @nvborisenko 
I just tested it, I can see that it reports the test to ReportPortal, but an empty report without any steps or actual logs (see below attached log and screenshots),
@nvborisenko  can you please check that it reports also the logs to the ReportPortal.

ReportPortal.Shared.89552.log :  
[ReportPortal.Shared.89552.log](https://github.com/TestCentric/testcentric-gui/files/4485332/ReportPortal.Shared.89552.log)

test that I ran from Nunit console runner : 
![sametestwithlogs](https://user-images.githubusercontent.com/28862779/79423678-b3347380-7fc7-11ea-9ef5-4a88a325256d.PNG)

the same test I ran from TestCentric 1.3.3:
![missinglogs](https://user-images.githubusercontent.com/28862779/79423730-c9423400-7fc7-11ea-8bc1-96467d9b6591.PNG)

**Comment by CharliePoole** [comment] 2020-04-16 07:11
@nvborisenko Are you able to tell whether this is TestCentri's or Report Portal's problem?

**Comment by nvborisenko** [comment] 2020-04-16 08:27
This is RP issue. I guess @eddie101AMR executed tests with shadow copy enabled. In this case runner doesn't copy one assembly, which is referenced implicitly, to shadowed location.

@eddie101AMR please try to disable shadow copy in TC options, and execute tests again.

**Comment by eddie101AMR** [comment] 2020-04-16 08:53
Thanks @nvborisenko ,
I disabled shadow copy in TestCentric and it's working,
the shadow copy will not affect anything else, am I right ?

**Comment by nvborisenko** [comment] 2020-04-16 09:41
@CharliePoole I propose to disable shadow copy by default as it is done in nunit runner.

**Comment by CharliePoole** [comment] 2020-04-16 19:58
@nvborisenko It's obviously trivial to change the default for a boolean switch. Unfortunately, it's not quite so simple... :disappointed: 

NUnit can work with or without shadow copy. The intention is to leave it up to the runner. In the case of the old NUnit V2 GUI (which is the basis for TestCentric GUI 1.x)  shadow copy is used so that the user can modify the files while they are loaded. This is a key issue for any testing UI.

There are various ways to solve the problem, but for 1.x, I think we are stuck with the way we have used up to now. I have some ideas about this. Primarily, it will require a sequence like this...

1. Discover all tests and display them. Save anything needed and unload the assemblies.
2. When run is requested, reload the assemblies.

It remains to be seen how efficiently this can be done. Ideally, we should save enough information so that reloading an unchanged assembly takes no significant time. That's not trivial, of course. BTW, that's how the VS Test Explorer operates. In that case, we are called in a completely separate process and have to repeat the discovery, which is time-consuming.

In the meantime, it's my feeling that changing the default would harm more users than it would help.

If you could create a separate issue for this, including the specific problem it causes for you, it would be very helpful.

**Comment by CharliePoole** [comment] 2020-04-17 14:19
Closing this as a result of #561, which allows the ReportPortal extension to run, albeit requiring ShadowCopy to be turned off. We'll need more info and time to examine that problem and to determine why this particular extension needs it to be off. 

@eddie101AMR You asked if this will affect anything else... depending on specific details, you may have difficulty re-compiling while the tests are open in the GUI. I'll wait to see a new issue on this after the 1.3.3 release.

**Closed** 2020-04-17 14:20 UTC
Labels: is:bug, pri:critical

**Comment by nvborisenko** [comment] 2020-04-17 14:34
Thank you @CharliePoole for your great support.

**Comment by CharliePoole** [comment] 2020-04-17 14:47
@nvborisenko Of course, you get the best support when you uncover a bug that embarasses me! :wink:

**Comment by eddie101AMR** [comment] 2020-04-17 15:50
Thanks you @CharliePoole  for the great and fast support!!
Have a great day
