### ISSUE TITLE
Crashes on startup when .NET 5.0 RC1 is installed

### ISSUE THREAD

**Issue by jpapp05** [TestCentric/testcentric-gui#601] opened 2020-09-23 23:14 UTC
**Describe the bug**
When launching the GUI it crashes on startup

**To Reproduce**
1. Install .NET 5,0 RC1 SDKs
2. Run app
3. Check event logs for error

**Expected behavior**
It opens without issue.

**Screenshots**
Application: testcentric.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.Version+VersionResult.SetFailure(ParseFailureKind, System.String)
   at System.Version.TryParseVersion(System.String, VersionResult ByRef)
   at System.Version.Parse(System.String)
   at System.Version..ctor(System.String)
   at TestCentric.Engine.Services.RuntimeFrameworkService.FindDotNetCoreFrameworks()
   at TestCentric.Engine.Services.RuntimeFrameworkService.StartService()
   at TestCentric.Engine.Services.ServiceManager.StartServices()
   at TestCentric.Engine.TestEngine.Initialize()
   at TestCentric.Engine.TestEngine.NUnit.Engine.ITestEngine.get_Services()
   at TestCentric.Gui.Model.TestServices..ctor(NUnit.Engine.ITestEngine)
   at TestCentric.Gui.Model.TestModel..ctor(NUnit.Engine.ITestEngine, System.String)
   at TestCentric.Gui.Model.TestModel.CreateTestModel(NUnit.Engine.ITestEngine, TestCentric.Gui.CommandLineOptions)
   at TestCentric.Gui.AppEntry.Main(System.String[])
   at TestCentric.Gui.Class1.Main(System.String[])

**Environment (please complete the following information):**
 - 1.4.0;  I would install 1.4.1 but there are no stand-alone binaries published.  
 - OS: Windows 10
 - Target Runtime: 4.7.2; but .NET 5.0 RC1 is installed.

![image](https://user-images.githubusercontent.com/39598625/94083360-c984fd80-fdb7-11ea-92ef-734a32c73b77.png)

**Comment by CharliePoole** [comment] 2020-09-24 01:28
This is a duplicate of #579, which was fixed in the 1.4.1 release. If I understand you correctly, you installed 1.4.0 using the zip package, which is not present in the 1.4.1 release. It was either not created or created but not uploaded. I'm hoping for the latter, which will give the quickest resolution. I'll check and get back to you.

As a workaround, the chocolatey package, `testcentric-gui-1.4.1.nupkg`, should have all the same files in tools directory. You can download it, change the extension to .zip and extract those files if you like.

**Comment by CharliePoole** [comment] 2021-01-14 18:56
I've verified that this was fixed with #579 but I never got back here to close it till now.

**Closed by CharliePoole** 2021-01-14 18:56 UTC
Labels: Bug, Needs Confirmation
