### ISSUE TITLE
Stop Button to interrupt infinite loop

### ISSUE THREAD

**Issue by MartinZec** [TestCentric/testcentric-gui#139] opened 2018-10-29 12:55 UTC
Hello,

In NUnit2 the stop button was also interrupting infinite loops and the cleanup and teardown was called. Up to now this feature is not available in NUnit3 with testcentric.

Is is planed to enable this feature in NUnit3/testcentric to interrupt infinite loops with the stop button from the GUI?

Best regards,
Martin

**Comment by CharliePoole** [comment] 2018-10-29 12:58
This needs to be tested against the current master.

**Comment by MartinZec** [comment] 2019-02-26 10:31
I tried with NUnit 3.10.1 and 3.11, in both versions the testcentric Alpha 2.0 Stop button did not stop/interrupt a while(true) loop inside the test.

**Comment by CharliePoole** [comment] 2019-02-26 14:59
OK, I'll take this as confirmed, even if by the same guy. :smiley:

**Comment by MartinZec** [comment] 2019-02-27 16:36
Issue is still there with 1.0.0-Alpha3.

**Comment by CharliePoole** [comment] 2019-02-27 16:47
That was quick! I'll take a closer look when I get a chance.

**Comment by CharliePoole** [comment] 2019-03-18 16:43
Here's the problem. The engine let's you pass a boolean argument to `ITestRunner.StopRun` indicating whether to do a cooperative (false) or forced (true) shutdown.

For the coooperative shutdown, all teardowns run and we get an event saying the run is complete. For a forced shutdown, it happens immediately. We use a cooperative shutdown in the GUI.

As an experiment, I tried using a forced shutdown. What I found is that the engine never signals that the run is complete. Even though we cancelled the run, most of the GUI thinks it's still ongoing and various menu items remain disabled. This is not good and it's an engine problem.

If this gets resolved in the GUI, we can then look at using a forced shutdown. However, I don't think we want to do that as our first choice, so we need to consider how to start with a coooperative shutdown and escalate to a forced shutdown after some elapsed time. If possible, I'd like to see that logic in the engine itself.

I'm marking this as an engine problem and taking it out of the release milestone.

**Comment by CharliePoole** [comment] 2019-07-14 02:52
This issue was duplicated by #337 and fixed in PR #359.

In summary, the framework was fixed so that the next version will terminate correctly and the copy of the engine that is used by TestCentric GUI was patched to force cancellation of earlier framework versions after a five-second delay.

**Closed by CharliePoole** 2019-07-14 02:52 UTC
Labels: is:bug, nunit, pri:normal

**Comment by MartinZec** [comment] 2019-10-08 13:20
OneTimeTearDown and TearDown are not called after the 5 second delay.
I use an COM port, which is closed in OneTimeTearDown and TearDown.

After using the Stop button, the COM port is still open since OneTimeTearDown and TearDown are not called.
Using testcnetric 1.0.1, NUnit Framework 3.12.0.0

**Comment by MartinZec** [comment] 2019-10-08 13:22
Why is a 5 seconds delay added?

**Comment by CharliePoole** [comment] 2019-10-08 13:53
Because of an error in the framework, we have to do a hack. Eventually, the framework will be updated so the hack won't be needed. But to allow for folks with an older version of the framework, it has to be left in. Therefore, we wait 5 seconds to see if the framework has terminated properly. Does that make sense?

Of course, based on what you wrote, the hack may not be working. :disappointed:

**Comment by CharliePoole** [comment] 2019-10-08 13:54
I'm traveling tomorrow but I will get back to this and try to confirm the problem later in the week.

**Comment by MartinZec** [comment] 2019-10-08 14:07
Thank you for the explanation for those 5 secondes delay.

After 5 seconds the Run button is active again and the Stop button is grayed out.
So in a bigger scope it works.

The issue I am facing is that the OneTimeTearDown and TearDown are not called, and by this the COM port is still open and cannot be reopened when I press the Run button again.

**Comment by CharliePoole** [comment] 2019-10-08 14:23
Yes, there are essentially two failure modes: not stopping at all and stopping without cleanup.

We are able to compensate for the first but not the second. By the time control is returned to the GUI, the tests have ended without running the teardowns.

**Comment by MartinZec** [comment] 2019-10-08 14:39
It stops actually after 5-6 seconds, always (without teardown)
Maybe I was a bit impatient there/not aware about the 5 seconds feature. Sorry for that.

There is only one issue, the mentioned second one.

**Comment by MartinZec** [comment] 2019-10-15 07:55
Will there be a fix for the "no teardown call after Stop button pressed"?
