### ISSUE TITLE
Application silently crashes on start on Windows 10

### ISSUE THREAD

**Issue by AI1718** [TestCentric/testcentric-gui#591] opened 2020-05-07 07:20 UTC
Application silently crashes on start. Event viewer shows:
=================================
_Application: testcentric.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Version+VersionResult.SetFailure(ParseFailureKind, System.String)
   at System.Version.TryParseComponent(System.String, System.String, VersionResult ByRef, Int32 ByRef)
   at System.Version.TryParseVersion(System.String, VersionResult ByRef)
   at System.Version.Parse(System.String)
   at System.Version..ctor(System.String)
   at TestCentric.Engine.Services.RuntimeFrameworkService.FindDotNetCoreFrameworks()
   at TestCentric.Engine.Services.RuntimeFrameworkService.StartService()
   at TestCentric.Engine.Services.ServiceManager.StartServices()
   at TestCentric.Engine.TestEngine.Initialize()
   at TestCentric.Engine.TestEngine.NUnit.Engine.ITestEngine.get_Services()
   at TestCentric.Gui.Model.TestServices..ctor(NUnit.Engine.ITestEngine)
   at TestCentric.Gui.Model.TestModel..ctor(NUnit.Engine.ITestEngine, System.String)
   at TestCentric.Gui.Model.TestModel.CreateTestModel(NUnit.Engine.ITestEngine, TestCentric.Gui.CommandLineOptions)
   at TestCentric.Gui.AppEntry.Main(System.String[])
   at TestCentric.Gui.Class1.Main(System.String[])_
=================================
After inspecting the source code, I found the following piece of code in RuntimeFrameworkService.cs:
var fullVersion = new Version(dir.Name),
where dir.Name points to dotnetcore installtion C:\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App

I inspected that dir and found:
1.0.4
1.0.5
1.1.1
1.1.2
2.0.0
2.0.9
2.1.11
2.1.12
2.1.13
2.1.16
2.1.17
2.1.3-servicing-26724-03
2.1.4
2.1.6
2.1.7
2.1.8
2.1.9
2.2.2
2.2.3
2.2.5
2.2.6
2.2.7
2.2.8
3.1.2
3.1.3

Obviously 2.1.3-servicing-26724-03  caused the problem.

To fix issue change:

`var fullVersion = new Version(dir.Name);`

to

   Version fullVersion;               
  try
                {
                    fullVersion = new Version(dir.Name);
                }
                catch {
                    continue;
                }
Environment :
 - TestCentric Version:  1.4.0
 - OS: Windows 10 Ent 2016 LTSB

**Comment by CharliePoole** [comment] 2020-05-07 08:11
This is a duplicate of #579 which is fixed in master. I'll do a 1.4.1 release in a day or two.

Thanks for your report.

**Closed** 2020-05-07 08:12 UTC
